// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALusUrzoK-UrxmZOq3DyPeHuPzrEVeVPA',
    appId: '1:392900372701:web:d890e9b6b20cd8b8051334',
    messagingSenderId: '392900372701',
    projectId: 'min-crm-934e0',
    authDomain: 'min-crm-934e0.firebaseapp.com',
    storageBucket: 'min-crm-934e0.firebasestorage.app',
    measurementId: 'G-JVP6S88GY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNtNbOp-qQGQpYDncHTo1Cmmoi1u9rFE',
    appId: '1:392900372701:android:22f3e03cfbcf11e2051334',
    messagingSenderId: '392900372701',
    projectId: 'min-crm-934e0',
    storageBucket: 'min-crm-934e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyStmgJ69MOodZaL-FVL5iJcWqP3tJ920',
    appId: '1:392900372701:ios:f0ccfd1cd29b9978051334',
    messagingSenderId: '392900372701',
    projectId: 'min-crm-934e0',
    storageBucket: 'min-crm-934e0.firebasestorage.app',
    iosBundleId: 'com.example.minCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyStmgJ69MOodZaL-FVL5iJcWqP3tJ920',
    appId: '1:392900372701:ios:f0ccfd1cd29b9978051334',
    messagingSenderId: '392900372701',
    projectId: 'min-crm-934e0',
    storageBucket: 'min-crm-934e0.firebasestorage.app',
    iosBundleId: 'com.example.minCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALusUrzoK-UrxmZOq3DyPeHuPzrEVeVPA',
    appId: '1:392900372701:web:265a804da7dece01051334',
    messagingSenderId: '392900372701',
    projectId: 'min-crm-934e0',
    authDomain: 'min-crm-934e0.firebaseapp.com',
    storageBucket: 'min-crm-934e0.firebasestorage.app',
    measurementId: 'G-ZD5GDZ3786',
  );
}
